#:import ShadowBox widgets.containers.ShadowBox
#:import Text widgets.inputs.Text
#:import IconButton widgets.buttons.IconButton
#:import CameraLayout widgets.camera.CameraLayout

#:import HrBox widgets.phys-box.hr.HrBox
#:import HrvBox widgets.phys-box.hrv.HrvBox

## Container for Camera and Graph

<Home>:
    padding: dp(14)
    spacing: dp(16)

    BoxLayout:
        orientation: 'vertical'
        Text:
            size_hint_y: 0.05
            text: "Phys-App"
            valign: "middle"
            halign: "left"

        BoxLayout:
            spacing: dp(10)
            
            ## Camera Section 
            AnchorLayout:
                anchor_y: 'top'
                size_hint_x: 0.4
                ShadowBox:
                    radius: [dp(8)] ## Rounded 16dp
                    elevation: 2
                    size_hint: 1, 0.7
                    padding: dp(16)
                    spacing: dp(8)
                    orientation: "vertical" 
                    BoxLayout:
                        size_hint_y: .1
                        orientation: 'horizontal'
                        AnchorLayout:
                            anchor_x: 'left'
                            anchor_y: 'center'
                            Text:
                                text: "Camera Feed"
                                font_name: app.fonts.body
                                font_size: app.fonts.size.h3
                                valign: "middle"
                                halign: "left"
                                color: app.colors.black
                        AnchorLayout:
                            anchor_x: 'right'
                            anchor_y: 'center'
                            IconButton:
                                size_hint: None, None
                                size: dp(16), dp(16)
                                source: app.resource_path('assets/icons/camera-solid.png')
                    
                    BoxLayout:
                        size_hint_y: 0.5
                        CameraLayout:
                            id: camera_layout

                    BoxLayout:
                        size_hint_y: .1
                        height: dp(32)
                        orientation: 'horizontal'
                        padding: [dp(16), 0]  # Optional: horizontal padding
                        spacing: dp(8)
                        # Status Text
                        Text:
                            text: "Status Camera: On" if camera_layout.camera_active else "Status Camera: Paused"
                            font_name: app.fonts.body
                            font_size: app.fonts.size.h5
                            color: app.colors.primary if camera_layout.camera_active else app.colors.danger
                            valign: "middle"
                            halign: "left"
                            size_hint_x: 1
                        # Icon Buttons
                        BoxLayout:
                            orientation: 'horizontal'
                            size_hint_x: None
                            height: dp(16)
                            width: dp(40)  # Adjust width as needed
                            spacing: dp(8)
                            IconButton:
                                size_hint: None, None
                                size: dp(16), dp(16)
                                pos_hint: {"center_y": 0.5}
                                on_release: camera_layout.toggle_camera()
                                source: app.resource_path('assets/icons/pause.png') if camera_layout.camera_active else app.resource_path('assets/icons/play-button.png') 
                            IconButton:
                                size_hint: None, None
                                size: dp(16), dp(16)
                                pos_hint: {"center_y": 0.5}
                                source: app.resource_path('assets/icons/circle-solid.png') if camera_layout.camera_active else app.resource_path('assets/icons/circle-red.png')
                    
            ## Physiology Section
            AnchorLayout:
                anchor_y: 'top'
                size_hint_x: 0.6
                ShadowBox:
                    radius: [dp(16)] ## Rounded 16dp
                    elevation: 2
                    size_hint: 1, 1
                    padding: dp(16)
                    spacing: dp(8)
                    orientation: "vertical" 

                    BoxLayout:
                        size_hint_y: 0.2
                        orientation: 'horizontal'

                        AnchorLayout:
                            anchor_x: 'left'
                            anchor_y: 'center'
                            Text:
                                text: "Physiology Signals"
                                font_name: app.fonts.body
                                valign: "middle"
                                halign: "left"
                                font_size: app.fonts.size.h3
                                color: app.colors.black

                    BoxLayout:
                        size_hint_y: 0.6
                        padding: dp(10)
                        radius: [dp(8)] ## Rounded 16dp
                        MatplotFigure:
                            id: figure_rppg

                    Widget:
                        size_hint_y: None
                        height: dp(12)


                    ## Physiology Status StatusIndicator
                    BoxLayout:
                        size_hint: 1, 0.4
                        padding: dp(8)
                        spacing: dp(8)
                        HrBox:
                            id: hr_box
                            label: "Heart Rate"
                            unit: "BPM"

                        # HrvBox:
                        #   id: hrv_box
                        #   label: "Hrv Rate"
                        #   unit: "ms"

                    BoxLayout:
                        size_hint: 1, 0.4
                        padding: dp(8)
                        spacing: dp(8)
                        HrvBox:
                            id: sdnn_box
                            label: "SDNN"
                            unit: "ms"
                        
                        HrvBox:
                            id: rmssd_box
                            label: "RMSSD"
                            unit: "ms"


                    # BoxLayout:
                    #    size_hint: 1, 0.4
                    #    padding: dp(8)
                    #    spacing: dp(8)

                     